volumes:
  cache:
  db_data:

services:
  volume-init:
    volumes:
      - cache:/cache

  php-exec:
    depends_on:
      volume-init:
        condition: service_completed_successfully
    volumes:
      - ./:/var/www/
      - cache:/cache
      - ./auth.json:/config/composer/auth.json:ro

  php:
    depends_on:
      volume-init:
        condition: service_completed_successfully
    volumes:
      - ./:/var/www/
      - cache:/cache
      - ./auth.json:/config/composer/auth.json:ro

  worker:
    depends_on:
      volume-init:
        condition: service_completed_successfully
    volumes:
      - ./:/var/www/
      - cache:/cache
      - ./auth.json:/config/composer/auth.json:ro

  nginx:
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage

[[- if eq .Database "postgres" ]]

  db_app:
    volumes:
      - db_data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
[[- else if eq .Database "mysql" ]]

  db_app:
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
[[- else ]]

  db_app:
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
[[- end ]]

  markdown-linter:
    volumes:
      - ./:/workdir
[[- if .AddE2E ]]

  e2e-playwright:
    volumes:
      - ./:/var/www/
      - cache:/cache
[[- end ]]

  gomplate:
    volumes:
      - ./:/workdir
