volumes:
  {{snakecase ProjectShortName}}_cache:
    external: true
  mariadb_data:

services:
  php-exec:
    volumes:
      - ./:/var/www/
      - {{snakecase ProjectShortName}}_cache:/cache
      - ./auth.json:/config/composer/auth.json:ro

  php:
    volumes:
      - ./:/var/www/
      - {{snakecase ProjectShortName}}_cache:/cache
      - ./auth.json:/config/composer/auth.json:ro

  worker:
    volumes:
      - ./:/var/www/
      - {{snakecase ProjectShortName}}_cache:/cache
      - ./auth.json:/config/composer/auth.json:ro

  nginx:
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage

  mariadb:
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
