{{$dockerTag := "" }}

{{- if eq PhpVersion "8.4"}}
    {{- $dockerTag = "1.5.0" }}
{{- else if eq PhpVersion "8.3"}}
    {{- $dockerTag = "1.8.0" }}
{{- else}}
    {{- $dockerTag = "0.5.0" }}
{{- end -}}

secrets:
  composer_auth:
    file: ${COMPOSER_AUTH_FILE:-./auth.json}

services:
  php-exec:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    entrypoint: ["fixuid", "-q"]
    image: ghcr.io/specsnl/php{{ PhpVersion | replace "."  "" }}:builder_nodejs-{{ $dockerTag }}
    profiles: [exec]
    environment:
      COREPACK_DEFAULT_TO_LATEST: 0
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0

  php:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      context: .
      dockerfile: php/Dockerfile
      target: builder-local
      secrets:
        - composer_auth
    secrets:
      - composer_auth

  worker:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      context: .
      dockerfile: php/Dockerfile
      target: builder-local
      secrets:
        - composer_auth
    restart: unless-stopped
    command:
      - bash
      - -c
      - "trap : 3 ; wait-for-it mariadb:3306 --strict --timeout=20 -- wait-for-it redis:6379 --strict --timeout=20 -- php artisan queue:listen --sleep=10 & wait"
    environment:
      PHP_COMPOSER_INSTALL_DEV: false
    depends_on:
      - php
      - redis
      - mariadb

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      secrets:
        - composer_auth
    depends_on:
      - php
    environment:
      CGI_HOST: "php.${COMPOSE_PROJECT_NAME}_default"
    labels:
      - dev.orbstack.domains={{toKebabCase ProjectShortName}}.local
      - dev.orbstack.http-port=80

  mariadb:
    image: mariadb:11.8.6-noble
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    labels:
      - dev.orbstack.domains=db.{{toKebabCase ProjectShortName}}.local

  redis:
    image: redis:7.4.2-bookworm
    labels:
      - dev.orbstack.domains=redis.{{toKebabCase ProjectShortName}}.local

  mailpit:
    image: axllent/mailpit:v1.22.3
    labels:
      - dev.orbstack.domains=mail.{{toKebabCase ProjectShortName}}.local
      - dev.orbstack.http-port=8025
