# Config options: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: laravel/framework
        update-types: [version-update:semver-major]
    labels:
      - dependencies
      - php
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm
    groups:
      vite:
        patterns:
          - vite
          - laravel-vite-plugin
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      specsnl-actions:
        patterns:
          - "specsnl/github-actions*"
  - package-ecosystem: docker
    directories:
      - /php
      - /nginx
    schedule:
      interval: weekly
    ignore:
      - dependency-name: alpine
        update-types: [version-update:semver-major, version-update:semver-minor]
    labels:
      - dependencies
      - docker
    groups:
      specsnl-php-images:
        patterns:
          - "specsnl/php*"
