__delimiters:
  left: "[["
  right: "]]"

ProjectName: My Acme Project
ProjectShortName: acme-12
ProjectDescription: This Laravel project is scaffolded using specsnl/specs-cli using the specsnl/specs-laravel-project.
PhpVersion:
  - "8.5"
  - "8.4"
  - "8.3"
RepoName: specsnl/project
ComposerLicense:
  - MIT
  - proprietary
IssuePrefix: ACME
Database:
  - postgres
  - mariadb
  - mysql
AddBugSnag: false

computed:
  DockerDbPort: >-
    [[ eq .Database "postgres" | ternary "5432" "3306" ]]

  DbOrbStackDomain: >-
    db.[[ .ProjectShortName | toKebabCase ]].local
  DbLabel: >-
    [[ eq .Database "postgres" | ternary "PostgreSQL" (eq .Database "mysql" | ternary "MySQL" "MariaDB") ]]
  DbConnection: >-
    [[ eq .Database "postgres" | ternary "pgsql" (eq .Database "mysql" | ternary "mysql" "mariadb") ]]
  DbHost: >-
    [[ .Database ]]
  DbPort: >-
    [[ eq .Database "postgres" | ternary "5432" "3306" ]]
  DbDatabase: >-
    [[ .ProjectShortName | toSnakeCase ]]
  DbUsername: >-
    [[ .ProjectShortName | toSnakeCase ]]
  DbPassword: password

  Php85DockerTag: "0.5.4" # Latest version: https://github.com/specsnl/php85/releases/latest
  Php84DockerTag: "1.5.4" # Latest version: https://github.com/specsnl/php84/releases/latest
  Php83DockerTag: "1.8.4" # Latest version: https://github.com/specsnl/php83/releases/latest
  PhpDockerTag: >-
    [[ eq .PhpVersion "8.4" | ternary .Php84DockerTag (eq .PhpVersion "8.3" | ternary .Php83DockerTag .Php85DockerTag) ]]

hooks:
  post-use:
    - task md:fixstyle
    - git init
    - git add .
