__delimiters:
  left: "[["
  right: "]]"

ProjectName: My Acme Project
ProjectShortName: acme
ProjectDescription: This Laravel project is scaffolded using specsnl/specs-cli using the specsnl/specs-laravel-project.
PhpVersion:
  - "8.5"
  - "8.4"
  - "8.3"
RepoName: specsnl/project
ComposerLicense:
  - MIT
  - proprietary
IssuePrefix: ACME
Database:
  - postgres
  - mariadb
  - mysql
AddBugSnag: false
AddFilament: false
AddE2E: false

computed:
  DockerDbPort: >-
    [[ eq .Database "postgres" | ternary "5432" "3306" ]]

  DbOrbStackDomain: >-
    db.[[ .ProjectShortName | toKebabCase ]].local
  DbLabel: >-
    [[ eq .Database "postgres" | ternary "PostgreSQL" (eq .Database "mysql" | ternary "MySQL" "MariaDB") ]]
  DbConnection: >-
    [[ eq .Database "postgres" | ternary "pgsql" .Database ]]
  DbHost: db_app
  DbPort: >-
    [[ eq .Database "postgres" | ternary "5432" "3306" ]]
  DbDatabase: >-
    [[ .ProjectShortName | toSnakeCase ]]
  DbUsername: >-
    [[ .ProjectShortName | toSnakeCase ]]
  DbPassword: password

  # PHP Images
  Php85DockerTag: "0.5.9" # Latest version: https://github.com/specsnl/php85/releases/latest
  Php84DockerTag: "1.5.9" # Latest version: https://github.com/specsnl/php84/releases/latest
  Php83DockerTag: "1.8.9" # Latest version: https://github.com/specsnl/php83/releases/latest
  PhpDockerTag: >-
    [[ eq .PhpVersion "8.4" | ternary .Php84DockerTag (eq .PhpVersion "8.3" | ternary .Php83DockerTag .Php85DockerTag) ]]

  # Database images
  PostgresImageTag: "postgres:18.6-trixie" # Latest version: https://hub.docker.com/_/postgres/tags
  MysqlImageTag: "mysql:8.4.11" # Latest version: https://hub.docker.com/_/mysql/tags
  MariadDbImageTag: "mariadb:11.8.9-noble" # Latest version: https://hub.docker.com/_/mariadb/tags
  DbImageTag: >-
    [[ eq .Database "postgres" | ternary .PostgresImageTag (eq .Database "mysql" | ternary .MysqlImageTag .MariadDbImageTag) ]]

hooks:
  post-use:
    - git init
    - task setup:env-file:local
    - task md:fixstyle
    - git add .
