__delimiters:
  left: "[["
  right: "]]"

ProjectName: My Acme Project
ProjectShortName: acme-12
ProjectDescription: This Laravel project is scaffolded using Boilr-tool (<https://github.com/Ilyes512/boilr>) using the boilr-laravel-project-template (<https://github.com/specsnl/boilr-laravel-project>).
PhpVersion:
  - "8.5"
  - "8.4"
  - "8.3"
RepoName: specsnl/project
ComposerLicense:
  - MIT
  - proprietary
IssuePrefix: ACME
Database:
  - postgres
  - mariadb

computed:
  DockerDbPort: >-
    [[ eq .Database "postgres" | ternary "5432" "3306" ]]

  DbConnection: >-
    [[ eq .Database "postgres" | ternary "pgsql" "mariadb" ]]
  DbHost: >-
    [[ .Database ]]
  DbPort: >-
    [[ eq .Database "postgres" | ternary "5432" "3306" ]]
  DbDatabase: >-
    [[ .ProjectShortName | toSnakeCase ]]
  DbUsername: >-
    [[ .ProjectShortName | toSnakeCase ]]
  DbPassword: password
