# https://taskfile.dev
version: '3.50'

tasks:

  install:
    desc: Install composer dependencies
    preconditions:
      - sh: test -f auth.json
        msg: 'Missing auth.json file. Please run task setup:auth!'
    cmds:
      - task: cmd:install

  update:
    desc: Install composer dependencies (including all dependencies)
    cmds:
      - task: :setup:auth
      - task: :dc:run:php-exec
        vars:
          SUB_CMD: 'composer update --with-all-dependencies'

  cmd:*:
    desc: Run a composer command inside the php service
    vars:
      COMPOSER_CMD: '{{ index .MATCH 0 }}'
    cmds:
      - task: :dc:run:php
        vars:
          SUB_CMD: 'composer {{ .COMPOSER_CMD }} {{ .SUB_CMD }}'
          CLI_ARGS: '{{ .CLI_ARGS }}'

  script:*:
    desc: Run a composer script
    vars:
      SCRIPT: '{{ index .MATCH 0 }}'
    cmds:
      - task: cmd:run
        vars:
          SUB_CMD: '{{ .SCRIPT }}'
          CLI_ARGS: '-- {{ .CLI_ARGS }}'
